server:
  port: 8888

spring:
  application:
    name : config-service
  cloud:
    config:
      server:
        git:
          uri : file:///Users/cjenm/Development/personal/local-repo # macbook pro's path

